# Generated by Django 4.1.4 on 2022-12-17 13:05

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('email_id', models.EmailField(default='', max_length=50)),
                ('blog_desc', models.CharField(default='', max_length=5000)),
                ('blog_img', models.ImageField(upload_to='blog_img')),
                ('blog_category', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('email_id', models.EmailField(default='', max_length=50)),
                ('blog_id', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Contact_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Learn_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email_id', models.EmailField(default='', max_length=50)),
                ('content', models.CharField(default='', max_length=10000)),
                ('fields', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=100)),
                ('mobile_no', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('account_type', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=5000)),
                ('business_plan', models.CharField(default='', max_length=5000)),
                ('business_category', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
