# Generated by Django 4.1.4 on 2022-12-26 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_data',
            name='business_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
