# Generated by Django 4.1.4 on 2023-04-22 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Homepage', '0003_rename_user_id_profile_data_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_data',
            name='user_id',
        ),
        migrations.AddField(
            model_name='blog_data',
            name='user_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
