# Generated by Django 4.1.4 on 2023-04-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_remove_blog_data_user_id_blog_data_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_data',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
