# Generated by Django 4.1.4 on 2023-04-22 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_blog_data_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_data',
            name='user_id',
        ),
    ]
