# Generated by Django 4.1.4 on 2023-04-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_remove_blog_data_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
