# Generated by Django 4.1.4 on 2023-04-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_donationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationdata',
            name='order_id',
            field=models.TextField(default='', max_length=500),
        ),
    ]
