# Generated by Django 4.1.4 on 2023-04-23 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0008_alter_donationdata_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donationdata',
            old_name='order_id',
            new_name='payment_id',
        ),
    ]
